### ISSUE TITLE
Syncronization fails due to not enough integer space in info_prefixes6

### ISSUE THREAD

**Issue by summalajnen** [peeringdb/django-peeringdb#21]
Hi,

There is an issue with syncronization currently where an AS has entered a huge amount of IPv6 prefixes in their PeeringDB entry. See output below from a recent sync:

{'info_prefixes6': [u'Ensure this value is less than or equal to 2147483647.']} : errors: {'info_prefixes6': [u'Ensure this value is less than or equal to 2147483647.']}
info_prefixes6: 4294967295, dict: {'_validators': [], 'auto_created': False, 'rel': None, 'creation_counter': 42, 'validators': [<django.core.validators.MinValueValidator object at 0x7f991c4a1290>, <django.core.validators.MaxValueValidator object at 0x7f991c4a1890>], 'serialize': True, 'editable': True, '_unique': False, 'error_messages': {u'unique': <django.utils.functional.__proxy__ object at 0x7f99236f6450>, u'invalid_choice': <django.utils.functional.__proxy__ object at 0x7f99236f6250>, u'blank': <django.utils.functional.__proxy__ object at 0x7f99236f6410>, u'null': <django.utils.functional.__proxy__ object at 0x7f99236f63d0>, u'unique_for_date': <django.utils.functional.__proxy__ object at 0x7f99236f6490>, u'invalid': <django.utils.functional.__proxy__ object at 0x7f99237004d0>}, 'unique_for_year': None, '_error_messages': None, 'blank': True, 'help_text': u'', 'unique_for_date': None, '_verbose_name': None, 'db_index': False, 'is_relation': False, 'unique_for_month': None, 'null': True, 'primary_key': False, 'db_column': None, 'default': <class django.db.models.fields.NOT_PROVIDED at 0x7f991ffa7ef0>, '_choices': [], 'column': 'info_prefixes6', 'name': 'info_prefixes6', 'concrete': True, 'max_length': None, 'db_tablespace': '', 'cached_col': Col(peeringdb_network, django_peeringdb.Network.info_prefixes6), 'model': <class 'django_peeringdb.models.concrete.Network'>, 'attname': 'info_prefixes6', 'verbose_name': u'info prefixes6'}
Traceback (most recent call last):
  File "/usr/local/bin/peeringdb", line 11, in <module>
    load_entry_point('peeringdb==0.6.0', 'console_scripts', 'peeringdb')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/peeringdb/cli.py", line 167, in sync
    db.sync()
  File "/usr/local/lib/python2.7/dist-packages/peeringdb/localdb.py", line 124, in sync
    call_command('pdb_sync', interactive=False)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 120, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django_peeringdb/management/commands/pdb_sync.py", line 91, in handle
    self.sync(tables, pk, limit=limit)
  File "/usr/local/lib/python2.7/dist-packages/django_peeringdb/management/commands/pdb_sync.py", line 98, in sync
    self.update_db(cls, self.get_objs(cls, pk=pk, **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/django_peeringdb/management/commands/pdb_sync.py", line 180, in update_db
    self._sync(cls, row)
  File "/usr/local/lib/python2.7/dist-packages/django_peeringdb/management/commands/pdb_sync.py", line 149, in _sync
    sync.sync_obj(cls, row)
  File "/usr/local/lib/python2.7/dist-packages/django_peeringdb/sync.py", line 40, in sync_obj
    raise e
django.core.exceptions.ValidationError: {'info_prefixes6': [u'Ensure this value is less than or equal to 2147483647.']}

A possible fix for this would be to change the following model in django_peeringdb/models/abstract.py:
info_prefixes6 = models.PositiveIntegerField(null=True, blank=True)

To the following:
info_prefixes6 = models.BigIntegerField(null=True, blank=True)

I've hot-patched my installation of django-peeringdb and haven't seen any issues with it. But there might be other parts of the model(s) that should be using BigInt instead? Or is there any other way to bypass this issue?

//Viktor

**Comment by vegu** [comment]
Interesting, we have a value validator on the peeringdb server that should have prevented this. I have fixed the value for now, will need to investigate how it go through in the first place.

Sync should work correctly again.

**Comment by vegu** [comment]
The server is supposed to limit to a max value of 50000 - as such a bigint is not required in the schema here, but it appears there seems to be a bug where the validator does not trigger correctly on the server side when saving the data. 

Once i have more information i will open a ticket in the other repository. Closing this one.

Thanks for the report.

**Comment by vegu** [comment]
This appears to have been a left over value from before we added the validator on the server - how it went unnoticed until now i don't know :) In any case issue should be resolved.
