### ISSUE TITLE
Sync fails on countrycode XK

### ISSUE THREAD

**Issue by Jterbeest** [peeringdb/django-peeringdb#3]
When doing a fresh install, the sync fails on the XK countrycode (the provisional code given to Kosovo):
`Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/jterbeest/.virtualenvs/luminara/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/Users/jterbeest/.virtualenvs/luminara/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/jterbeest/.virtualenvs/luminara/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/jterbeest/.virtualenvs/luminara/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/Users/jterbeest/.virtualenvs/luminara/lib/python2.7/site-packages/django_peeringdb/management/commands/pdb_sync.py", line 85, in handle
    self.sync(tables)
  File "/Users/jterbeest/.virtualenvs/luminara/lib/python2.7/site-packages/django_peeringdb/management/commands/pdb_sync.py", line 92, in sync
    self.update_db(cls, self.get_objs(cls))
  File "/Users/jterbeest/.virtualenvs/luminara/lib/python2.7/site-packages/django_peeringdb/management/commands/pdb_sync.py", line 127, in update_db
    sync.sync_obj(cls, row)
  File "/Users/jterbeest/.virtualenvs/luminara/lib/python2.7/site-packages/django_peeringdb/sync.py", line 25, in sync_obj
    obj.full_clean()
  File "/Users/jterbeest/.virtualenvs/luminara/lib/python2.7/site-packages/django/db/models/base.py", line 1171, in full_clean
    raise ValidationError(errors)
django.core.exceptions.ValidationError: {'country': [u"Value u'XK' is not a valid choice."]}`

This is caused by the value being in your database but missing from the country list that is currently in django_countries.

**Comment by benmaddison** [comment]
Hi Johan,

Add:
`COUNTRIES_OVERRIDE = {
   'XK': 'Kosovo',
}`
to your project's `settings.py`.

Cheers,

Ben

**Comment by Jterbeest** [comment]
That's what I did but don't you think it should be added then to the main project?

**Comment by benmaddison** [comment]
Just had a look at [the ISO website](https://www.iso.org/obp/ui/#search) to see if it's there, and it's not, even under the reserved codes. I don't know where the XK code actually comes from, but in the absence of an entry in the ISO3166 registry, it's probably appropriate that it isn't included by default.

**Comment by grizz** [comment]
It's in the red box at the top of http://peeringdb.github.io/django-peeringdb/ - yes, not included by default because it's not a defacto ISO standard.

There's a thread somewhere, @mahtin can probably be more specific, but off the top of my head, the X* ISO codes are reserved user defined codes for when countries change faster than ISO; thus, according to [Wikipedia](https://en.wikipedia.org/wiki/Kosovo):

> XK is a "user assigned" ISO 3166 code not designated by the standard, but used by the European Commission, Switzerland, the Deutsche Bundesbank and other organisations.

Other organisations include PeeringDB :)

**Comment by mahtin** [comment]
What @grizz said!
