### ISSUE TITLE
pdb_sync backtraces & stops on PeeringDB's data consistency error

### ISSUE THREAD

**Issue by paravoid** [peeringdb/django-peeringdb#31]
OK, so first off, this sounds like a legitimate PeeringDB data consistency error that probably shouldn't happen:
```
$ curl https://www.peeringdb.com/api/net/18102
{"meta": {}, "data": [{"id": 18102, "org_id": 18985, "org": {"id": 18985, "name": "NTT America, Inc.", "website": "", "notes": "", "net_set": [18102], "fac_set": [], "ix_set": [], "address1": "", "address2": "", "city": "", "country": "", "state": "", "zipcode": "", "created": "2018-01-18T21:21:59Z", "updated": "2018-01-18T21:30:06Z", "status": "deleted"}, "name": "NTT America", "aka": "", "website": "", "asn": 263, "looking_glass": "", "route_server": "", "irr_as_set": "", "info_type": "Not Disclosed", "info_prefixes4": 0, "info_prefixes6": 0, "info_traffic": "", "info_ratio": "Not Disclosed", "info_scope": "Not Disclosed", "info_unicast": false, "info_multicast": false, "info_ipv6": false, "notes": "", "policy_url": "", "policy_general": "Open", "policy_locations": "Not Required", "policy_ratio": false, "policy_contracts": "Not Required", "netfac_set": [], "netixlan_set": [], "poc_set": [], "created": "2018-10-23T01:52:34Z", "updated": "2018-10-23T09:32:04Z", "status": "ok"}]}

$ curl https://www.peeringdb.com/api/org/18985
{"meta": {"error": "Not found."}}
```
(also confirmed on PeeringDB's web interface).

That breaks pdb_sync, which fails with:
```
$ ./manage.py pdb_sync
org last update 1540292393 0 changed
data to be processed 0
fac last update 1540226972 0 changed
data to be processed 0
net last update 1540285561 7 changed
data to be processed 7
org.18985 not found locally, trying to fetch object... 
Traceback (most recent call last):
  File "/venv/peerassist/lib/python3.5/site-packages/django_peeringdb/management/commands/pdb_sync.py", line 151, in _sync 
    sync.sync_obj(cls, row)
  File "/venv/peerassist/lib/python3.5/site-packages/django_peeringdb/sync.py", line 40, in sync_obj
    raise e
  File "/venv/peerassist/lib/python3.5/site-packages/django_peeringdb/sync.py", line 29, in sync_obj
    obj.full_clean()
  File "/venv/peerassist/lib/python3.5/site-packages/django/db/models/base.py", line 1152, in full_clean 
    raise ValidationError(errors)
django.core.exceptions.ValidationError: {'org': ['organization instance with id 18985 does not exist.']}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/venv/peerassist/lib/python3.5/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/venv/peerassist/lib/python3.5/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/venv/peerassist/lib/python3.5/site-packages/django/core/management/base.py", line 316, in run_from_argv 
    self.execute(*args, **cmd_options)
  File "/venv/peerassist/lib/python3.5/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/venv/peerassist/lib/python3.5/site-packages/django_peeringdb/management/commands/pdb_sync.py", line 91, in handle 
    self.sync(tables, pk, limit=limit)
  File "/venv/peerassist/lib/python3.5/site-packages/django_peeringdb/management/commands/pdb_sync.py", line 98, in sync
    self.update_db(cls, self.get_objs(cls, pk=pk, **kwargs))
  File "/venv/peerassist/lib/python3.5/site-packages/django_peeringdb/management/commands/pdb_sync.py", line 182, in update_db
    self._sync(cls, row)
  File "/venv/peerassist/lib/python3.5/site-packages/django_peeringdb/management/commands/pdb_sync.py", line 166, in _sync 
    r = self.rpc.get(field, int(m.group(1)), depth=0)
  File "/venv/peerassist/lib/python3.5/site-packages/twentyc/rpc/client.py", line 117, in get
    return self._load(self._request(typ, id=id, params=kwargs))
  File "/venv/peerassist/lib/python3.5/site-packages/twentyc/rpc/client.py", line 88, in _load
    self._throw(res, data)
  File "/venv/peerassist/lib/python3.5/site-packages/twentyc/rpc/client.py", line 68, in _throw
    raise NotFoundException("%d %s" % (res.status_code, err))
twentyc.rpc.client.NotFoundException: 404 Not found.
```

I'm honestly unsure what would be the correct behavior here. It should probably at least catch the exception and print a friendlier error message?

**Comment by grizz** [comment]
I think this is handled by #158, so closing. Please re-open if anyone disagrees.
