### ISSUE TITLE
Missing ix when doing fresh sync

### ISSUE THREAD

**Issue by Jterbeest** [peeringdb/django-peeringdb#4]
When doing a fresh sync, somehow an Internet Exchange is not present:

`Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/jterbeest/.virtualenvs/luminara/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/Users/jterbeest/.virtualenvs/luminara/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/jterbeest/.virtualenvs/luminara/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/jterbeest/.virtualenvs/luminara/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/Users/jterbeest/.virtualenvs/luminara/lib/python2.7/site-packages/django_peeringdb/management/commands/pdb_sync.py", line 85, in handle
    self.sync(tables)
  File "/Users/jterbeest/.virtualenvs/luminara/lib/python2.7/site-packages/django_peeringdb/management/commands/pdb_sync.py", line 92, in sync
    self.update_db(cls, self.get_objs(cls))
  File "/Users/jterbeest/.virtualenvs/luminara/lib/python2.7/site-packages/django_peeringdb/management/commands/pdb_sync.py", line 127, in update_db
    sync.sync_obj(cls, row)
  File "/Users/jterbeest/.virtualenvs/luminara/lib/python2.7/site-packages/django_peeringdb/sync.py", line 25, in sync_obj
    obj.full_clean()
  File "/Users/jterbeest/.virtualenvs/luminara/lib/python2.7/site-packages/django/db/models/base.py", line 1171, in full_clean
    raise ValidationError(errors)
django.core.exceptions.ValidationError: {'ix': [u'internet exchange instance with id 1032 does not exist.']}`

**Comment by vegu** [comment]
Can't reproduce, can you paste your pip freeze output?

Also output from before the traceback if you can (mainly the parts where it starts fetching and processing the various api endpoints)

**Comment by grizz** [comment]
No response, closing unless we hear more.
